#include "pebble.h"

#include "Adventure.h"
#include "Battle.h"
#include "Character.h"
#include "DungeonCrawl.h"
#include "Location.h"
#include "LocationInternal.h"
#include "Logging.h"
#include "MiniDungeon.h"
#include "Monsters.h"
#include "Story.h"
	
#if INCLUDE_DUNGEON_CRAWL

enum
{
	DUNGEON_ENTRANCE = 0,
	DUNGEON_FLOOR_1,
	DUNGEON_FLOOR_1_END,
	DUNGEON_FLOOR_2,
	DUNGEON_FLOOR_2_END,
	DUNGEON_FLOOR_3,
	DUNGEON_FLOOR_3_END,
	DUNGEON_FLOOR_4,
	DUNGEON_FLOOR_4_END,
	DUNGEON_FLOOR_5,
	DUNGEON_FLOOR_5_END,
	DUNGEON_FLOOR_6,
	DUNGEON_FLOOR_6_END,
	DUNGEON_FLOOR_7,
	DUNGEON_FLOOR_7_END,
	DUNGEON_FLOOR_8,
	DUNGEON_FLOOR_8_END,
	DUNGEON_FLOOR_9,
	DUNGEON_FLOOR_9_END,
	DUNGEON_FLOOR_10,
	DUNGEON_FLOOR_10_END,
	DUNGEON_FLOOR_11,
	DUNGEON_FLOOR_11_END,
	DUNGEON_FLOOR_12,
	DUNGEON_FLOOR_12_END,
	DUNGEON_FLOOR_13,
	DUNGEON_FLOOR_13_END,
	DUNGEON_FLOOR_14,
	DUNGEON_FLOOR_14_END,
	DUNGEON_FLOOR_15,
	DUNGEON_FLOOR_15_END,
	DUNGEON_FLOOR_16,
	DUNGEON_FLOOR_16_END,
	DUNGEON_FLOOR_17,
	DUNGEON_FLOOR_17_END,
	DUNGEON_FLOOR_18,
	DUNGEON_FLOOR_18_END,
	DUNGEON_FLOOR_19,
	DUNGEON_FLOOR_19_END,
	DUNGEON_FLOOR_20,
	DUNGEON_DRAGONS_ROOM,
	DUNGEON_TREASURE_ROOM,
};

enum
{
	DUNGEON_RAT = 0,
	DUNGEON_GOBLIN,
	DUNGEON_WIZARD,
	DUNGEON_ZOMBIE,
	DUNGEON_TURTLE,
	DUNGEON_LICH,
	DUNGEON_DRAGON,
};

static Location locationList[] = 
{
	{
		.name = "Dungeon Entrance",
		.type = LOCATIONTYPE_FIXED,
		.numberOfAdjacentLocations = 1,
		.adjacentLocations = {DUNGEON_FLOOR_1},
		.numberOfBackgroundImages = 1,
		.backgroundImages = {RESOURCE_ID_IMAGE_DUNGEONSTRAIGHT},
	},
	{
		.name = "Floor 1",
		.type = LOCATIONTYPE_PATH,
		.numberOfAdjacentLocations = 2,
		.adjacentLocations = {DUNGEON_ENTRANCE, DUNGEON_FLOOR_1_END},
		.length = 30,
		.baseLevel = 1,
		.numberOfBackgroundImages = 3,
		.backgroundImages = {RESOURCE_ID_IMAGE_DUNGEONSTRAIGHT, RESOURCE_ID_IMAGE_DUNGEONLEFT, RESOURCE_ID_IMAGE_DUNGEONRIGHT},
		.numberOfMonsters = 1,
		.monsters = {DUNGEON_RAT},
		.encounterChance = 15,
	},
	{
		.name = "Floor 1 Stairs",
		.type = LOCATIONTYPE_FIXED,
		.numberOfAdjacentLocations = 1,
		.adjacentLocations = {DUNGEON_FLOOR_2},
		.numberOfBackgroundImages = 1,
		.backgroundImages = {RESOURCE_ID_IMAGE_NEWFLOOR},
	},
	{
		.name = "Floor 2",
		.type = LOCATIONTYPE_PATH,
		.numberOfAdjacentLocations = 2,
		.adjacentLocations = {DUNGEON_FLOOR_1_END, DUNGEON_FLOOR_2_END},
		.length = 30,
		.baseLevel = 2,
		.numberOfBackgroundImages = 3,
		.backgroundImages = {RESOURCE_ID_IMAGE_DUNGEONSTRAIGHT, RESOURCE_ID_IMAGE_DUNGEONLEFT, RESOURCE_ID_IMAGE_DUNGEONRIGHT},
		.numberOfMonsters = 1,
		.monsters = {DUNGEON_RAT},
		.encounterChance = 15,
	},
	{
		.name = "Floor 2 Stairs",
		.type = LOCATIONTYPE_FIXED,
		.numberOfAdjacentLocations = 1,
		.adjacentLocations = {DUNGEON_FLOOR_3},
		.numberOfBackgroundImages = 1,
		.backgroundImages = {RESOURCE_ID_IMAGE_NEWFLOOR},
	},
	{
		.name = "Floor 3",
		.type = LOCATIONTYPE_PATH,
		.numberOfAdjacentLocations = 2,
		.adjacentLocations = {DUNGEON_FLOOR_2_END, DUNGEON_FLOOR_3_END},
		.length = 30,
		.baseLevel = 3,
		.numberOfBackgroundImages = 3,
		.backgroundImages = {RESOURCE_ID_IMAGE_DUNGEONSTRAIGHT, RESOURCE_ID_IMAGE_DUNGEONLEFT, RESOURCE_ID_IMAGE_DUNGEONRIGHT},
		.numberOfMonsters = 2,
		.monsters = {DUNGEON_RAT, DUNGEON_GOBLIN},
		.encounterChance = 15,
	},
	{
		.name = "Floor 3 Stairs",
		.type = LOCATIONTYPE_FIXED,
		.numberOfAdjacentLocations = 1,
		.adjacentLocations = {DUNGEON_FLOOR_4},
		.numberOfBackgroundImages = 1,
		.backgroundImages = {RESOURCE_ID_IMAGE_NEWFLOOR},
	},
	{
		.name = "Floor 4",
		.type = LOCATIONTYPE_PATH,
		.numberOfAdjacentLocations = 2,
		.adjacentLocations = {DUNGEON_FLOOR_3_END, DUNGEON_FLOOR_4_END},
		.length = 30,
		.baseLevel = 4,
		.numberOfBackgroundImages = 3,
		.backgroundImages = {RESOURCE_ID_IMAGE_DUNGEONSTRAIGHT, RESOURCE_ID_IMAGE_DUNGEONLEFT, RESOURCE_ID_IMAGE_DUNGEONRIGHT},
		.numberOfMonsters = 3,
		.monsters = {DUNGEON_RAT, DUNGEON_GOBLIN, DUNGEON_GOBLIN},
		.encounterChance = 15,
	},
	{
		.name = "Floor 4 Stairs",
		.type = LOCATIONTYPE_FIXED,
		.numberOfAdjacentLocations = 1,
		.adjacentLocations = {DUNGEON_FLOOR_5},
		.numberOfBackgroundImages = 1,
		.backgroundImages = {RESOURCE_ID_IMAGE_NEWFLOOR},
	},
	{
		.name = "Floor 5",
		.type = LOCATIONTYPE_PATH,
		.numberOfAdjacentLocations = 2,
		.adjacentLocations = {DUNGEON_FLOOR_4_END, DUNGEON_FLOOR_5_END},
		.length = 30,
		.baseLevel = 5,
		.numberOfBackgroundImages = 3,
		.backgroundImages = {RESOURCE_ID_IMAGE_DUNGEONSTRAIGHT, RESOURCE_ID_IMAGE_DUNGEONLEFT, RESOURCE_ID_IMAGE_DUNGEONRIGHT},
		.numberOfMonsters = 3,
		.monsters = {DUNGEON_RAT, DUNGEON_GOBLIN, DUNGEON_WIZARD},
		.encounterChance = 15,
	},
	{
		.name = "Floor 5 Stairs",
		.type = LOCATIONTYPE_FIXED,
		.numberOfAdjacentLocations = 1,
		.adjacentLocations = {DUNGEON_FLOOR_6},
		.numberOfBackgroundImages = 1,
		.backgroundImages = {RESOURCE_ID_IMAGE_NEWFLOOR},
	},
	{
		.name = "Floor 6",
		.type = LOCATIONTYPE_PATH,
		.numberOfAdjacentLocations = 2,
		.adjacentLocations = {DUNGEON_FLOOR_5_END, DUNGEON_FLOOR_6_END},
		.length = 30,
		.baseLevel = 6,
		.numberOfBackgroundImages = 3,
		.backgroundImages = {RESOURCE_ID_IMAGE_DUNGEONSTRAIGHT, RESOURCE_ID_IMAGE_DUNGEONLEFT, RESOURCE_ID_IMAGE_DUNGEONRIGHT},
		.numberOfMonsters = 4,
		.monsters = {DUNGEON_RAT, DUNGEON_GOBLIN, DUNGEON_WIZARD, DUNGEON_WIZARD},
		.encounterChance = 15,
	},
	{
		.name = "Floor 6 Stairs",
		.type = LOCATIONTYPE_FIXED,
		.numberOfAdjacentLocations = 1,
		.adjacentLocations = {DUNGEON_FLOOR_7},
		.numberOfBackgroundImages = 1,
		.backgroundImages = {RESOURCE_ID_IMAGE_NEWFLOOR},
	},
	{
		.name = "Floor 7",
		.type = LOCATIONTYPE_PATH,
		.numberOfAdjacentLocations = 2,
		.adjacentLocations = {DUNGEON_FLOOR_6_END, DUNGEON_FLOOR_7_END},
		.length = 30,
		.baseLevel = 7,
		.numberOfBackgroundImages = 3,
		.backgroundImages = {RESOURCE_ID_IMAGE_DUNGEONSTRAIGHT, RESOURCE_ID_IMAGE_DUNGEONLEFT, RESOURCE_ID_IMAGE_DUNGEONRIGHT},
		.numberOfMonsters = 4,
		.monsters = {DUNGEON_RAT, DUNGEON_GOBLIN, DUNGEON_WIZARD, DUNGEON_ZOMBIE},
		.encounterChance = 15,
	},
	{
		.name = "Floor 7 Stairs",
		.type = LOCATIONTYPE_FIXED,
		.numberOfAdjacentLocations = 1,
		.adjacentLocations = {DUNGEON_FLOOR_8},
		.numberOfBackgroundImages = 1,
		.backgroundImages = {RESOURCE_ID_IMAGE_NEWFLOOR},
	},
	{
		.name = "Floor 8",
		.type = LOCATIONTYPE_PATH,
		.numberOfAdjacentLocations = 2,
		.adjacentLocations = {DUNGEON_FLOOR_7_END, DUNGEON_FLOOR_8_END},
		.length = 30,
		.baseLevel = 8,
		.numberOfBackgroundImages = 3,
		.backgroundImages = {RESOURCE_ID_IMAGE_DUNGEONSTRAIGHT, RESOURCE_ID_IMAGE_DUNGEONLEFT, RESOURCE_ID_IMAGE_DUNGEONRIGHT},
		.numberOfMonsters = 4,
		.monsters = {DUNGEON_GOBLIN, DUNGEON_WIZARD, DUNGEON_ZOMBIE, DUNGEON_ZOMBIE},
		.encounterChance = 15,
	},
	{
		.name = "Floor 8 Stairs",
		.type = LOCATIONTYPE_FIXED,
		.numberOfAdjacentLocations = 1,
		.adjacentLocations = {DUNGEON_FLOOR_9},
		.numberOfBackgroundImages = 1,
		.backgroundImages = {RESOURCE_ID_IMAGE_NEWFLOOR},
	},
	{
		.name = "Floor 9",
		.type = LOCATIONTYPE_PATH,
		.numberOfAdjacentLocations = 2,
		.adjacentLocations = {DUNGEON_FLOOR_8_END, DUNGEON_FLOOR_9_END},
		.length = 30,
		.baseLevel = 9,
		.numberOfBackgroundImages = 3,
		.backgroundImages = {RESOURCE_ID_IMAGE_DUNGEONSTRAIGHT, RESOURCE_ID_IMAGE_DUNGEONLEFT, RESOURCE_ID_IMAGE_DUNGEONRIGHT},
		.numberOfMonsters = 4,
		.monsters = {DUNGEON_GOBLIN, DUNGEON_WIZARD, DUNGEON_ZOMBIE, DUNGEON_TURTLE},
		.encounterChance = 15,
	},
	{
		.name = "Floor 9 Stairs",
		.type = LOCATIONTYPE_FIXED,
		.numberOfAdjacentLocations = 1,
		.adjacentLocations = {DUNGEON_FLOOR_10},
		.numberOfBackgroundImages = 1,
		.backgroundImages = {RESOURCE_ID_IMAGE_NEWFLOOR},
	},
	{
		.name = "Floor 10",
		.type = LOCATIONTYPE_PATH,
		.numberOfAdjacentLocations = 2,
		.adjacentLocations = {DUNGEON_FLOOR_9_END, DUNGEON_FLOOR_10_END},
		.length = 30,
		.baseLevel = 10,
		.numberOfBackgroundImages = 3,
		.backgroundImages = {RESOURCE_ID_IMAGE_DUNGEONSTRAIGHT, RESOURCE_ID_IMAGE_DUNGEONLEFT, RESOURCE_ID_IMAGE_DUNGEONRIGHT},
		.numberOfMonsters = 4,
		.monsters = {DUNGEON_WIZARD, DUNGEON_ZOMBIE, DUNGEON_TURTLE, DUNGEON_TURTLE},
		.encounterChance = 15,
	},
	{
		.name = "Floor 10 Stairs",
		.type = LOCATIONTYPE_FIXED,
		.numberOfAdjacentLocations = 1,
		.adjacentLocations = {DUNGEON_FLOOR_11},
		.numberOfBackgroundImages = 1,
		.backgroundImages = {RESOURCE_ID_IMAGE_NEWFLOOR},
	},
	{
		.name = "Floor 11",
		.type = LOCATIONTYPE_PATH,
		.numberOfAdjacentLocations = 2,
		.adjacentLocations = {DUNGEON_FLOOR_10_END, DUNGEON_FLOOR_11_END},
		.length = 30,
		.baseLevel = 11,
		.numberOfBackgroundImages = 3,
		.backgroundImages = {RESOURCE_ID_IMAGE_DUNGEONSTRAIGHT, RESOURCE_ID_IMAGE_DUNGEONLEFT, RESOURCE_ID_IMAGE_DUNGEONRIGHT},
		.numberOfMonsters = 4,
		.monsters = {DUNGEON_WIZARD, DUNGEON_ZOMBIE, DUNGEON_TURTLE, DUNGEON_LICH},
		.encounterChance = 15,
	},
	{
		.name = "Floor 11 Stairs",
		.type = LOCATIONTYPE_FIXED,
		.numberOfAdjacentLocations = 1,
		.adjacentLocations = {DUNGEON_FLOOR_12},
		.numberOfBackgroundImages = 1,
		.backgroundImages = {RESOURCE_ID_IMAGE_NEWFLOOR},
	},
	{
		.name = "Floor 12",
		.type = LOCATIONTYPE_PATH,
		.numberOfAdjacentLocations = 2,
		.adjacentLocations = {DUNGEON_FLOOR_11_END, DUNGEON_FLOOR_12_END},
		.length = 30,
		.baseLevel = 12,
		.numberOfBackgroundImages = 3,
		.backgroundImages = {RESOURCE_ID_IMAGE_DUNGEONSTRAIGHT, RESOURCE_ID_IMAGE_DUNGEONLEFT, RESOURCE_ID_IMAGE_DUNGEONRIGHT},
		.numberOfMonsters = 4,
		.monsters = {DUNGEON_WIZARD, DUNGEON_ZOMBIE, DUNGEON_TURTLE, DUNGEON_LICH},
		.encounterChance = 15,
	},
	{
		.name = "Floor 12 Stairs",
		.type = LOCATIONTYPE_FIXED,
		.numberOfAdjacentLocations = 1,
		.adjacentLocations = {DUNGEON_FLOOR_13},
		.numberOfBackgroundImages = 1,
		.backgroundImages = {RESOURCE_ID_IMAGE_NEWFLOOR},
	},
	{
		.name = "Floor 13",
		.type = LOCATIONTYPE_PATH,
		.numberOfAdjacentLocations = 2,
		.adjacentLocations = {DUNGEON_FLOOR_12_END, DUNGEON_FLOOR_13_END},
		.length = 30,
		.baseLevel = 13,
		.numberOfBackgroundImages = 3,
		.backgroundImages = {RESOURCE_ID_IMAGE_DUNGEONSTRAIGHT, RESOURCE_ID_IMAGE_DUNGEONLEFT, RESOURCE_ID_IMAGE_DUNGEONRIGHT},
		.numberOfMonsters = 4,
		.monsters = {DUNGEON_WIZARD, DUNGEON_ZOMBIE, DUNGEON_TURTLE, DUNGEON_LICH},
		.encounterChance = 15,
	},
	{
		.name = "Floor 13 Stairs",
		.type = LOCATIONTYPE_FIXED,
		.numberOfAdjacentLocations = 1,
		.adjacentLocations = {DUNGEON_FLOOR_14},
		.numberOfBackgroundImages = 1,
		.backgroundImages = {RESOURCE_ID_IMAGE_NEWFLOOR},
	},
	{
		.name = "Floor 14",
		.type = LOCATIONTYPE_PATH,
		.numberOfAdjacentLocations = 2,
		.adjacentLocations = {DUNGEON_FLOOR_10_END, DUNGEON_FLOOR_11_END},
		.length = 30,
		.baseLevel = 14,
		.numberOfBackgroundImages = 3,
		.backgroundImages = {RESOURCE_ID_IMAGE_DUNGEONSTRAIGHT, RESOURCE_ID_IMAGE_DUNGEONLEFT, RESOURCE_ID_IMAGE_DUNGEONRIGHT},
		.numberOfMonsters = 4,
		.monsters = {DUNGEON_WIZARD, DUNGEON_ZOMBIE, DUNGEON_TURTLE, DUNGEON_LICH},
		.encounterChance = 15,
	},
	{
		.name = "Floor 14 Stairs",
		.type = LOCATIONTYPE_FIXED,
		.numberOfAdjacentLocations = 1,
		.adjacentLocations = {DUNGEON_FLOOR_15},
		.numberOfBackgroundImages = 1,
		.backgroundImages = {RESOURCE_ID_IMAGE_NEWFLOOR},
	},
	{
		.name = "Floor 15",
		.type = LOCATIONTYPE_PATH,
		.numberOfAdjacentLocations = 2,
		.adjacentLocations = {DUNGEON_FLOOR_14_END, DUNGEON_FLOOR_15_END},
		.length = 30,
		.baseLevel = 15,
		.numberOfBackgroundImages = 3,
		.backgroundImages = {RESOURCE_ID_IMAGE_DUNGEONSTRAIGHT, RESOURCE_ID_IMAGE_DUNGEONLEFT, RESOURCE_ID_IMAGE_DUNGEONRIGHT},
		.numberOfMonsters = 4,
		.monsters = {DUNGEON_WIZARD, DUNGEON_ZOMBIE, DUNGEON_TURTLE, DUNGEON_LICH},
		.encounterChance = 15,
	},
	{
		.name = "Floor 15 Stairs",
		.type = LOCATIONTYPE_FIXED,
		.numberOfAdjacentLocations = 1,
		.adjacentLocations = {DUNGEON_FLOOR_16},
		.numberOfBackgroundImages = 1,
		.backgroundImages = {RESOURCE_ID_IMAGE_NEWFLOOR},
	},
	{
		.name = "Floor 16",
		.type = LOCATIONTYPE_PATH,
		.numberOfAdjacentLocations = 2,
		.adjacentLocations = {DUNGEON_FLOOR_15_END, DUNGEON_FLOOR_16_END},
		.length = 30,
		.baseLevel = 16,
		.numberOfBackgroundImages = 3,
		.backgroundImages = {RESOURCE_ID_IMAGE_DUNGEONSTRAIGHT, RESOURCE_ID_IMAGE_DUNGEONLEFT, RESOURCE_ID_IMAGE_DUNGEONRIGHT},
		.numberOfMonsters = 4,
		.monsters = {DUNGEON_WIZARD, DUNGEON_ZOMBIE, DUNGEON_TURTLE, DUNGEON_LICH},
		.encounterChance = 15,
	},
	{
		.name = "Floor 16 Stairs",
		.type = LOCATIONTYPE_FIXED,
		.numberOfAdjacentLocations = 1,
		.adjacentLocations = {DUNGEON_FLOOR_17},
		.numberOfBackgroundImages = 1,
		.backgroundImages = {RESOURCE_ID_IMAGE_NEWFLOOR},
	},
	{
		.name = "Floor 17",
		.type = LOCATIONTYPE_PATH,
		.numberOfAdjacentLocations = 2,
		.adjacentLocations = {DUNGEON_FLOOR_16_END, DUNGEON_FLOOR_17_END},
		.length = 30,
		.baseLevel = 17,
		.numberOfBackgroundImages = 3,
		.backgroundImages = {RESOURCE_ID_IMAGE_DUNGEONSTRAIGHT, RESOURCE_ID_IMAGE_DUNGEONLEFT, RESOURCE_ID_IMAGE_DUNGEONRIGHT},
		.numberOfMonsters = 4,
		.monsters = {DUNGEON_WIZARD, DUNGEON_ZOMBIE, DUNGEON_TURTLE, DUNGEON_LICH},
		.encounterChance = 15,
	},
	{
		.name = "Floor 17 Stairs",
		.type = LOCATIONTYPE_FIXED,
		.numberOfAdjacentLocations = 1,
		.adjacentLocations = {DUNGEON_FLOOR_18},
		.numberOfBackgroundImages = 1,
		.backgroundImages = {RESOURCE_ID_IMAGE_NEWFLOOR},
	},
	{
		.name = "Floor 18",
		.type = LOCATIONTYPE_PATH,
		.numberOfAdjacentLocations = 2,
		.adjacentLocations = {DUNGEON_FLOOR_17_END, DUNGEON_FLOOR_18_END},
		.length = 30,
		.baseLevel = 18,
		.numberOfBackgroundImages = 3,
		.backgroundImages = {RESOURCE_ID_IMAGE_DUNGEONSTRAIGHT, RESOURCE_ID_IMAGE_DUNGEONLEFT, RESOURCE_ID_IMAGE_DUNGEONRIGHT},
		.numberOfMonsters = 4,
		.monsters = {DUNGEON_WIZARD, DUNGEON_ZOMBIE, DUNGEON_TURTLE, DUNGEON_LICH},
		.encounterChance = 15,
	},
	{
		.name = "Floor 18 Stairs",
		.type = LOCATIONTYPE_FIXED,
		.numberOfAdjacentLocations = 1,
		.adjacentLocations = {DUNGEON_FLOOR_19},
		.numberOfBackgroundImages = 1,
		.backgroundImages = {RESOURCE_ID_IMAGE_NEWFLOOR},
	},
	{
		.name = "Floor 19",
		.type = LOCATIONTYPE_PATH,
		.numberOfAdjacentLocations = 2,
		.adjacentLocations = {DUNGEON_FLOOR_18_END, DUNGEON_FLOOR_19_END},
		.length = 30,
		.baseLevel = 19,
		.numberOfBackgroundImages = 3,
		.backgroundImages = {RESOURCE_ID_IMAGE_DUNGEONSTRAIGHT, RESOURCE_ID_IMAGE_DUNGEONLEFT, RESOURCE_ID_IMAGE_DUNGEONRIGHT},
		.numberOfMonsters = 4,
		.monsters = {DUNGEON_WIZARD, DUNGEON_ZOMBIE, DUNGEON_TURTLE, DUNGEON_LICH},
		.encounterChance = 15,
	},
	{
		.name = "Floor 19 Stairs",
		.type = LOCATIONTYPE_FIXED,
		.numberOfAdjacentLocations = 1,
		.adjacentLocations = {DUNGEON_FLOOR_20},
		.numberOfBackgroundImages = 1,
		.backgroundImages = {RESOURCE_ID_IMAGE_NEWFLOOR},
	},
	{
		.name = "Floor 20",
		.type = LOCATIONTYPE_PATH,
		.numberOfAdjacentLocations = 2,
		.adjacentLocations = {DUNGEON_FLOOR_19_END, DUNGEON_DRAGONS_ROOM},
		.length = 30,
		.baseLevel = 20,
		.numberOfBackgroundImages = 3,
		.backgroundImages = {RESOURCE_ID_IMAGE_DUNGEONSTRAIGHT, RESOURCE_ID_IMAGE_DUNGEONLEFT, RESOURCE_ID_IMAGE_DUNGEONRIGHT},
		.numberOfMonsters = 4,
		.monsters = {DUNGEON_WIZARD, DUNGEON_ZOMBIE, DUNGEON_TURTLE, DUNGEON_LICH},
		.encounterChance = 15,
	},
	{
		.name = "Dragon's Room",
		.type = LOCATIONTYPE_FIXED,
		.numberOfAdjacentLocations = 1,
		.adjacentLocations = {DUNGEON_TREASURE_ROOM},
		.numberOfBackgroundImages = 1,
		.backgroundImages = {RESOURCE_ID_IMAGE_DUNGEONSTRAIGHT},
		.numberOfMonsters = 1,
		.monsters = {DUNGEON_DRAGON},
		.baseLevel = 20,
		.arrivalFunction = ShowBattleWindow,
	},
	{
		.name = "Treasure Room",
		.type = LOCATIONTYPE_FIXED,
		.numberOfAdjacentLocations = 0,
		.numberOfBackgroundImages = 1,
		.backgroundImages = {RESOURCE_ID_IMAGE_DUNGEONDEADEND},
		.arrivalFunction = ShowEndWindow,
	},
};

static MonsterDef monsters[] =
{
	{
		.name = "Rat",
		.imageId = RESOURCE_ID_IMAGE_RAT,
		.extraFireDefenseMultiplier = 100,
		.extraIceDefenseMultiplier = 100,
		.extraLightningDefenseMultiplier = 100,
		.powerLevel = 0,
		.healthLevel = 0,
		.defenseLevel = 0,
		.magicDefenseLevel = 0,
		.allowPhysicalAttack = true,
		.goldScale = 1
	},

	{
		.name = "Goblin",
		.imageId = RESOURCE_ID_IMAGE_GOBLIN,
		.extraFireDefenseMultiplier = 100,
		.extraIceDefenseMultiplier = 200,
		.extraLightningDefenseMultiplier = 100,
		.powerLevel = 1,
		.healthLevel = 1,
		.defenseLevel = 1,
		.magicDefenseLevel = 0,
		.allowPhysicalAttack = true,
		.goldScale = 2
	},

	{
		.name = "Wizard",
		.imageId = RESOURCE_ID_IMAGE_WIZARD,
		.extraFireDefenseMultiplier = 100,
		.extraIceDefenseMultiplier = 100,
		.extraLightningDefenseMultiplier = 100,
		.powerLevel = 1,
		.healthLevel = 1,
		.defenseLevel = 1,
		.magicDefenseLevel = 3,
		.allowMagicAttack = true,
		.goldScale = 3
	},

	{
		.name = "Zombie",
		.imageId = RESOURCE_ID_IMAGE_ZOMBIE,
		.extraFireDefenseMultiplier = 300,
		.extraIceDefenseMultiplier = 100,
		.extraLightningDefenseMultiplier = 100,
		.powerLevel = 2,
		.healthLevel = 1,
		.defenseLevel = 1,
		.magicDefenseLevel = 1,
		.allowPhysicalAttack = true,
		.goldScale = 2
	},

	{
		.name = "Turtle",
		.imageId = RESOURCE_ID_IMAGE_TURTLE,
		.extraFireDefenseMultiplier = 100,
		.extraIceDefenseMultiplier = 100,
		.extraLightningDefenseMultiplier = 600,
		.powerLevel = 1,
		.healthLevel = 2,
		.defenseLevel = 3,
		.magicDefenseLevel = 1,
		.allowPhysicalAttack = true,
		.goldScale = 1
	},

	{
		.name = "Lich",
		.imageId = RESOURCE_ID_IMAGE_LICH,
		.extraFireDefenseMultiplier = 100,
		.extraIceDefenseMultiplier = 600,
		.extraLightningDefenseMultiplier = 100,
		.powerLevel = 2,
		.healthLevel = 2,
		.defenseLevel = 3,
		.magicDefenseLevel = 1,
		.allowMagicAttack = true,
		.goldScale = 5
	},

	{
		.name = "Dragon",
		.imageId = RESOURCE_ID_IMAGE_DRAGON,
		.extraFireDefenseMultiplier = 100,
		.extraIceDefenseMultiplier = 100,
		.extraLightningDefenseMultiplier = 100,
		.powerLevel = 2,
		.healthLevel = 2,
		.defenseLevel = 2,
		.magicDefenseLevel = 2,
		.allowPhysicalAttack = true,
		.allowMagicAttack = true,
		.goldScale = 10,
		.preventRun = true,
	},
};

StoryState dungeonCrawlStoryState = {0};

void InitializeDungeonCrawl(void)
{
	dungeonCrawlStoryState.needsSaving = true;
	dungeonCrawlStoryState.currentLocationIndex = 0;
	dungeonCrawlStoryState.currentLocationDuration = 0;
	dungeonCrawlStoryState.currentPathDestination = 0;
	dungeonCrawlStoryState.mostRecentMonster = 0;
}

Story dungeonCrawlStory = 
{
	.gameNumber = DUNGEON_CRAWL_INDEX,
	.gameDataVersion = 1,
	.locationList = locationList,
	.monsterList = monsters,
	.initializeStory = InitializeDungeonCrawl,
};

void LaunchDungeonCrawl(void)
{
#if INCLUDE_DUNGEON_CRAWL
	dungeonCrawlStory.numberOfLocations = sizeof(locationList)/sizeof(Location);
	dungeonCrawlStory.numberOfMonsters = sizeof(monsters)/sizeof(MonsterDef);
	RegisterStory(&dungeonCrawlStory, &dungeonCrawlStoryState);
	DEBUG_LOG("Initialized locationList size = %d", sizeof(locationList));
	ShowAdventureWindow();
#endif	
}

#endif