#include "pebble.h"
	
#include "Menu.h"
#include "Slideshow.h"
#include "UILayers.h"

#if INCLUDE_SLIDESHOW

bool gUpdateSlideshow = false;
uint32_t iterator = 0;
Window *slideshowWindow = NULL;

const int resourceArray[] = 
{
	RESOURCE_ID_IMAGE_TITLE,
	RESOURCE_ID_IMAGE_BEACH,
	RESOURCE_ID_IMAGE_TREASURE_ROOM,
	RESOURCE_ID_IMAGE_TOMB_ENTRANCE,
	RESOURCE_ID_IMAGE_MOUNTAIN3,
	RESOURCE_ID_IMAGE_MOUNTAIN2,
	RESOURCE_ID_IMAGE_MOUNTAIN1,
	RESOURCE_ID_IMAGE_BOAT,
	RESOURCE_ID_IMAGE_SARCOPHAGUS,
	RESOURCE_ID_IMAGE_PYRAMID_EXTERIOR,
	RESOURCE_ID_IMAGE_WATERFALL_TOP,
	RESOURCE_ID_IMAGE_WATERFALL_BASE,
	RESOURCE_ID_IMAGE_MONSTER8,
	RESOURCE_ID_IMAGE_MONSTER9,
	RESOURCE_ID_IMAGE_MONSTER10,
	RESOURCE_ID_IMAGE_MONSTER11,
	RESOURCE_ID_IMAGE_MONSTER12,
	RESOURCE_ID_IMAGE_MONSTER13,
	RESOURCE_ID_IMAGE_MONSTER14,
	RESOURCE_ID_IMAGE_MONSTER15,
	RESOURCE_ID_IMAGE_MONSTER16,
	RESOURCE_ID_IMAGE_MONSTER17,
	RESOURCE_ID_IMAGE_MONSTER18,
	RESOURCE_ID_IMAGE_MONSTER19,
	RESOURCE_ID_IMAGE_MONSTER20,
	RESOURCE_ID_IMAGE_MONSTER21,
	RESOURCE_ID_IMAGE_MONSTER22,
	RESOURCE_ID_IMAGE_MONSTER23,
	RESOURCE_ID_IMAGE_MONSTER24,
	RESOURCE_ID_IMAGE_MONSTER25,
	RESOURCE_ID_IMAGE_MONSTER26,
	RESOURCE_ID_IMAGE_MONSTER27,
	RESOURCE_ID_IMAGE_MONSTER28,
	RESOURCE_ID_IMAGE_BOSS1,
	RESOURCE_ID_IMAGE_BOSS2,
	RESOURCE_ID_IMAGE_BOSS3,
	RESOURCE_ID_IMAGE_BOSS4,
	RESOURCE_ID_IMAGE_BOSS5,
	RESOURCE_ID_IMAGE_BOSS6,
	RESOURCE_ID_IMAGE_BOSS7,
	RESOURCE_ID_IMAGE_OASIS,
	RESOURCE_ID_IMAGE_DESERT1,
	RESOURCE_ID_IMAGE_DESERT2,
	RESOURCE_ID_IMAGE_DESERT3,
	RESOURCE_ID_IMAGE_CAVE_FIXED,
	RESOURCE_ID_IMAGE_FOREST1,
	RESOURCE_ID_IMAGE_FOREST2,
	RESOURCE_ID_IMAGE_FOREST3,
	RESOURCE_ID_IMAGE_RUINED_VILLAGE_EXTERIOR,
	RESOURCE_ID_IMAGE_DRAGON,
	RESOURCE_ID_IMAGE_LICH,
	RESOURCE_ID_IMAGE_WIZARD,
	RESOURCE_ID_IMAGE_TURTLE,
	RESOURCE_ID_IMAGE_ZOMBIE,
	RESOURCE_ID_IMAGE_RAT,
	RESOURCE_ID_IMAGE_GOBLIN,
	RESOURCE_ID_IMAGE_SHOP,
	RESOURCE_ID_IMAGE_REST,
	RESOURCE_ID_IMAGE_NEWFLOOR,
	RESOURCE_ID_IMAGE_DUNGEONDEADEND,
	RESOURCE_ID_IMAGE_DUNGEONSTRAIGHT,
	RESOURCE_ID_IMAGE_DUNGEONRIGHT,
	RESOURCE_ID_IMAGE_DUNGEONLEFT,
	RESOURCE_ID_IMAGE_ROAD1,
	RESOURCE_ID_IMAGE_ROAD2,
	RESOURCE_ID_IMAGE_ROAD3,
	RESOURCE_ID_IMAGE_VILLAGE_EXTERIOR,
	RESOURCE_ID_IMAGE_VILLAGE_INTERIOR,
	RESOURCE_ID_IMAGE_CAVE1,
	RESOURCE_ID_IMAGE_CAVE2,
	RESOURCE_ID_IMAGE_CAVE3,
	RESOURCE_ID_IMAGE_CELLAR,
	RESOURCE_ID_IMAGE_FOREST_CAVE,
};

void SlideshowMenuWindowAppear(Window *window)
{
	MenuAppear(window);
	slideshowWindow = window;
	gUpdateSlideshow = true;
}

void SlideshowMenuWindowDisappear(Window *window)
{
	slideshowWindow = NULL;
	gUpdateSlideshow = false;
	MenuDisappear(window);
}

MenuDefinition slideshowMenuDef = 
{
	.appear = SlideshowMenuWindowAppear,
	.disappear = SlideshowMenuWindowDisappear,
	.mainImageId = RESOURCE_ID_IMAGE_TITLE,
	.floorImageId = -1
};

void LaunchSlideshow(void)
{
	PushNewMenu(&slideshowMenuDef);
}

void UpdateSlideshow(void)
{
	++iterator;
	if(iterator >= sizeof(resourceArray)/sizeof(int))
		iterator = 0;

	slideshowMenuDef.mainImageId = resourceArray[iterator];
	if(slideshowWindow)
		LoadMainBmpImage(slideshowWindow, slideshowMenuDef.mainImageId, slideshowMenuDef.floorImageId);	
}

#endif
